project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"
    - "*qmd"

execute:
  freeze: auto  # re-render only when source changes

date-modified: last-modified
title-block-style: none

format:
  html:
    theme:
      light: lumen
      dark: cyborg
    css: styles.css
    toc: true
    toc-expand: true
    toc-depth: 4
    link-external-newwindow: true

website:
  title: "Bioinformatics guidance page"
  site-url: https://scienceparkstudygroup.github.io/software_information/
  repo-url: https://github.com/ScienceParkStudyGroup/software_information/
  repo-actions: [source, issue]
  page-navigation: true
  search: 
    location: sidebar
    type: overlay
    show-item-context: true
  page-footer:  
    center: | 
      Copyright 2023, Nina Dombrowski,    
      Last modified: {{< meta date-modified >}}  
  
  sidebar:
    style: "docked"
    collapse-level: 2

    contents:
      - text: "Welcome page"
        href: index.qmd

      - section: "Getting Started"
        contents:
          - text: "Code documentation"
            href: source/cli/code_doc.qmd

          - section: "Using the command line"
            href: source/cli/cli.qmd
            contents:
              - text: "Setting up a bash command line"
                href: source/cli/cli_installation.qmd
              - text: "Getting started with bash"
                href: source/cli/cli_basics.qmd
              - text: "Manipulating files with bash"
                href: source/cli/cli_file_manipulation.qmd

          - text: "Installing software"
            href: source/conda/conda.qmd

          - text: "Using R"
            href: source/R/readme.qmd

          - section: "Using an HPC"
            href: source/cli/hpc_usage.qmd
            contents:
              - text: "Start working on an HPC"
                href: source/cli/slurm_basics.qmd

      - section: "Sequence data analyses"
        href: source/metagenomics/readme.qmd

        contents:
          - section: "Core tools"
            contents:
              - source/core_tools/busco.qmd
              - source/core_tools/diamond.qmd
              - source/core_tools/hmmer.qmd
              - source/core_tools/ncbi.qmd
              - source/core_tools/prokka.qmd
              - source/core_tools/seqkit.qmd
              - source/classification/kraken2.qmd
              - source/classification/minimap2.qmd

          - section: "Amplicon analyses"
            href: source/Qiime/readme.qmd
            contents:
              - source/Qiime/3_evelyn_tutorial_notes.qmd
              - source/Qiime/OTU_table_analysis.qmd

          - section: "Functional annotation"
            contents:
              - source/metagenomics/interproscan_readme.qmd
              - source/metagenomics/fama_readme.qmd
              - source/metagenomics/metabolic.qmd
              - source/metagenomics/metacerberus.qmd
              - source/metagenomics/signalp6.qmd

          - section: "(Meta)genomics"
            contents:
              - source/nanopore/nanophase_how_to.qmd
              - source/metagenomics/atlas.qmd
              - source/metagenomics/flye.qmd
              - source/metagenomics/trycycler.qmd
              - source/metagenomics/checkm2.qmd
              - source/metagenomics/gtdb.qmd
              - source/metagenomics/pseudofinder.qmd
              - source/metagenomics/quast.qmd
              - source/metagenomics/dnaapler.qmd
              - source/metagenomics/bakta.qmd
              - source/metagenomics/motus.qmd

          - section: "Eukaryotic genomics"
            contents:
              - source/metagenomics/augustus.qmd
              - source/metagenomics/deeploc.qmd

          - section: "Fungal genomics"
            contents:
              - source/ITSx/itsx_readme.qmd
              - source/nanopore/nanoITS.qmd

          - section: "(Meta)transcriptomics"
            contents:
              - source/metatranscriptomics/sortmerna.qmd
              - source/metatranscriptomics/ribodetector.qmd
              - source/metatranscriptomics/trinity.qmd
              - source/metatranscriptomics/star.qmd
              - source/core_tools/bowtie.qmd
              - source/core_tools/samtools.qmd
              - source/core_tools/featurecounts.qmd
              - source/core_tools/rsem.qmd
              - source/metatranscriptomics/DSEq2.qmd

          - section: "Nanopore analyses"
            contents:
              - source/nanopore/filtlong.qmd
              - source/nanopore/nanoqc_readme.qmd
              - source/nanopore/nanoplot_readme.qmd
              - source/nanopore/porechop_readme.qmd
              - source/nanopore/chopper.qmd
              - source/nanopore/nanoclass.qmd
              - source/nanopore/nanoITS.qmd
              - source/nanopore/nanophase_how_to.qmd

          - section: "Phylogenomics"
            contents:
              - source/phylogenomics/bmge.qmd
              - source/phylogenomics/mafft.qmd
              - source/phylogenomics/iqtree2.qmd

          - section: "Quality control"
            contents:
              - source/metagenomics/fastqc_readme.qmd
              - source/metagenomics/multiqc.qmd
              - source/metatranscriptomics/fastp.qmd

          - section: "Sequence alignment"
            contents:
              - source/core_tools/bowtie.qmd
              - source/core_tools/samtools.qmd
              - source/core_tools/featurecounts.qmd

      - section: "Bioinformatics toolbox"
        href: source/core_tools/toolbox-readme.qmd
        contents:
          - source/core_tools/bash-for-loops.qmd

      - section: "Bioinformatic databases"
        contents:
          - source/core_tools/cog.qmd
          - source/core_tools/kegg_db.qmd
          - source/core_tools/ncbi_nr.qmd
          - source/core_tools/pfam_db.qmd
          - source/core_tools/pgap_db.qmd
          - source/core_tools/tigrfam_db.qmd

      # - section: "Phylogenomics"
      #   href: source/databases/readme.qmd
      #   contents:

      # - section: "Bioinformatic databases"

      # - section: "Tutorials"