project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"
    - "*qmd"


website:
  title: "Software"
  repo-url:  https://github.com/ScienceParkStudyGroup/software_information
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - source/cli/readme.qmd
      - source/R/readme.qmd
      - section: "Amplicon sequence analysis"
        contents:
          - source/Qiime/readme.qmd
      - section: "Metagenomics"
        contents:
          - source/metagenomics/readme.qmd
      - section: "Fungal genomics"
        contents:
          - source/ITSx/readme.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ScienceParkStudyGroup/software_information
  page-footer: "Copyright 2023, Nina Dombrowski" 

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



