project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"
    - "*qmd"

format:
  html:
    theme:
      light: lumen
      dark: cyborg
    date: last-modified
    css: styles.css
    toc: true
    toc-expand: true
    toc-depth: 4

website:
  title: "Bioinformatics guidance page"
  page-navigation: true
  page-footer:  
    center: | 
      Copyright 2023, Nina Dombrowski,    
      Last modified: {{< meta date >}} 
  
  sidebar:
    - id: "Welcome page"
      style: "docked"
      search: true
      collapse: true

      contents:
        - section: "Welcome page"
          href: index.qmd
          
          contents:
          - text: "Command line"
            href: source/cli/readme.qmd
          - text: "Installing software"
            href: source/conda/conda.qmd
          - text: "R"
            href: source/R/readme.qmd

          - section: "Amplicon analyses"
            contents:
              - source/Qiime/readme.qmd
              - source/Qiime/3_evelyn_tutorial_notes.qmd

          - section: "Nanopore analyses"
            contents:
              - source/nanopore/readme.qmd
              - source/nanopore/chopper.qmd
              - source/nanopore/nanoclass.qmd
              - source/nanopore/nanoITS.qmd
              - source/nanopore/nanoqc_readme.qmd
              - source/nanopore/nanoplot_readme.qmd
              - source/nanopore/porechop_readme.qmd

          - section: "Sequence classification"
            contents:
              - source/classification/kraken2.qmd
              - source/classification/minimap2.qmd

          - section: "Metagenomics"
            contents:
              - source/metagenomics/readme.qmd
              - source/metagenomics/fastqc_readme.qmd
              - source/metagenomics/interproscan_readme.qmd
              - source/metagenomics/fama_readme.qmd
              - source/metagenomics/metabolic.qmd
          
          - section: "Fungal genomics"
            contents:
              - source/ITSx/itsx_readme.qmd
              - source/nanopore/nanoITS.qmd

      tools:
        - icon: github
          href: https://github.com/ScienceParkStudyGroup/software_information

