project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"

website:
  title: "Software"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Fungal genomics"
        contents:
          - source/ITSx/readme.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



