project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"
    - "*qmd"

execute:
  freeze: auto  # re-render only when source changes

date-modified: last-modified
title-block-style: none

format:
  html:
    theme:
      light: lumen
      dark: cyborg
    css: styles.css
    toc: true
    toc-expand: true
    toc-depth: 4
    link-external-newwindow: true

website:
  title: "Bioinformatics guidance page"
  site-url: https://scienceparkstudygroup.github.io/software_information/
  repo-url: https://github.com/ScienceParkStudyGroup/software_information/
  repo-actions: [source, issue]
  page-navigation: true
  page-footer:  
    center: | 
      Copyright 2023, Nina Dombrowski,    
      Last modified: {{< meta date-modified >}}  
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2

    contents:
      - text: "Welcome page"
        href: index.qmd

      - section: "Getting Started"
        contents:
          - text: "Code documentation"
            href: source/cli/code_doc.qmd

          - section: "Using the command line"
            href: source/cli/cli.qmd
            contents:
              - text: "Setting up a bash command line"
                href: source/cli/cli_installation.qmd
              - text: "Getting started with bash"
                href: source/cli/cli_basics.qmd
              - text: "Manipulating files with bash"
                href: source/cli/cli_file_manipulation.qmd

          - text: "Installing software"
            href: source/conda/conda.qmd

          - text: "Using R"
            href: source/R/readme.qmd

          - section: "Using an HPC"
            href: source/cli/hpc_usage.qmd
            contents:
              - text: "Start working on an HPC"
                href: source/cli/slurm_basics.qmd

      - section: "Sequence data analyses"
        href: source/metagenomics/readme.qmd

        contents:
          - section: "Core tools"
            contents:
              - source/classification/kraken2.qmd
              - source/classification/minimap2.qmd

          - section: "Quality control"
            contents:
              - source/metagenomics/fastqc_readme.qmd
              - source/metatranscriptomics/fastp.qmd

          - section: "Functional annotation"
            contents:
              - source/metagenomics/interproscan_readme.qmd
              - source/metagenomics/fama_readme.qmd
              - source/metagenomics/metabolic.qmd

          - section: "Amplicon analyses"
            href: source/Qiime/readme.qmd
            contents:
              - source/Qiime/3_evelyn_tutorial_notes.qmd
              - source/Qiime/OTU_table_analysis.qmd

          - section: "(Meta)transcriptomics"
            contents:
              - source/metatranscriptomics/sortmerna.qmd
              - source/metatranscriptomics/trinity.qmd

          - section: "Nanopore analyses"
            contents:
              - source/nanopore/nanoqc_readme.qmd
              - source/nanopore/nanoplot_readme.qmd
              - source/nanopore/porechop_readme.qmd
              - source/nanopore/chopper.qmd
              - source/nanopore/nanoclass.qmd
              - source/nanopore/nanoITS.qmd

          - section: "Fungal genomics"
            contents:
              - source/ITSx/itsx_readme.qmd
              - source/nanopore/nanoITS.qmd

      # - section: "Phylogenomics"
      #   href: source/databases/readme.qmd
      #   contents:

      # - section: "Bioinformatic databases"
      #   href: source/databases/readme.qmd
      #   contents:

      # - section: "Tutorials"