project:
  type: website
  output-dir: docs
  render:
    - "!readme.md"
    - "*qmd"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-expand: false

website:
  title: "Software information"
  page-navigation: true
  page-footer: "Copyright 2023, Nina Dombrowski" 
  
  sidebar:
    - id: guide
      style: "docked"
      search: true
      collapse-level: 1

      contents:
        - section: "Guide"
          href: index.qmd
          
          contents:
          - text: "Command line"
            href: source/cli/readme.qmd
          - text: "R"
            href: source/R/readme.qmd
          
          - section: "Amplicomics"
            contents:
              - source/Qiime/readme.qmd
              - source/Qiime/3_evelyn_tutorial_notes.qmd
          
          - section: "Metagenomics"
            contents:
              - source/metagenomics/readme.qmd
          
          - section: "Fungal genomics"
            contents:
              - source/ITSx/readme.qmd

      tools:
        - icon: github
          href: https://github.com/ScienceParkStudyGroup/software_information



