
## General

On this website you can find documentation about software that might be useful for bioinformatic data analyses. Please note: This is very much a work in progress and the page will be slowly updated over time. 

If you want to add additional information you are welcome to do so. For now, feel free to send an email to <n.dombrowski@uva.nl> with a markdown, quarto or text file with all relevant information and I can integrate this into the webpage. In the future, a "how-to-add-your-own-information" section will be added as well.

On each page, you will find a note if the software is installed on Crunchomics in the introduction. Additionally, each page will give you a brief installation instruction as well as some basic information about using the tool.


### Tool list A-Z

- [FAMA](source/fama/readme.qmd)
- [FastQC](source/fastqc_readme.qmd)
- [Interproscan](source/interproscan/readme.qmd)
- [ITSx](source/ITSx/itsx_readme.qmd)
- [NanoClass](source/nanopore/nanoclass.qmd)
- [NanoITS](source/nanopore/nanoITS.qmd)
- [NanoPlot](source/nanopore/nanoplot_readme.qmd)
- [NanoQC](source/nanopore/nanoqc_readme.qmd)
- [Porechop](source/nanopore/porechop_readme.qmd)