---
toc-depth: 2

execute:
  eval: false

engine: knitr
---

<div style="text-align: justify">

## Introduction

In this section you will find documentation on how to use the Unix command-line interface Bash.

The Linux command-line interface (**CLI**) is an alternative to a graphical user interface (**GUI**) with which you are likely more familiar. Both interfaces allow a user to interact with an operating system. The key difference between the CLI and GUI is that the interaction with CLI is based on issuing commands. In contrast, the interaction with a GUI involves visual elements, such as windows, buttons, etc. CLI is often also referred to as the shell, terminal, console, prompt or various other names

**Bash** is a type of interpreter that processes shell commands. A shell interpreter takes commands in plain text format and calls the operating system to do something, for example changing a directory or modifying the content of some files. Bash itself stands for Bourne Again Shell and it is one of the popular command-line shells used to run other programs, many of which are useful for bioinformatic workflows.


