---
code-block-bg: true
code-block-border-left: "#31BAE9"
execute:
  eval: false
engine: knitr
bibliography: references.bib
---

## Kraken2

### Introduction

Kraken2 [@wood2019] is a taxonomic sequence classifier that assigns taxonomic labels to DNA sequences. Kraken examines the k-mers within a query sequence and uses the information within those k-mers to query a database. That database maps k-mers to the lowest common ancestor (LCA) of all genomes known to contain a given k-mer.

Available on Crunchomics: Kraken version 2.0.8-beta installed

### Installation

If you want to install kraken2 on your own, its best to install it via mamba.

If you do not have mamba (or conda) installed. Check out the installation instructions for [mamba](https://mamba.readthedocs.io/en/latest/mamba-installation.html#mamba-install) and [conda](https://crunchomics-documentation.readthedocs.io/en/latest/miniconda.html). Mamba is a newer version of conda and from experience faster but since its newer this might mean that not all software can yet be installed with mamba.

```{bash}
#setup new conda environment, which we name kraken2
mamba create --name kraken2 -c bioconda kraken2
```

### Usage

For detailed usage information, check out the [kraken2 manual](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown).

#### Build a kraken database

The command below will download NCBI taxonomic information, as well as the complete genomes in RefSeq for the bacterial, archaeal, and viral domains, along with the human genome and a collection of known vectors (UniVec_Core). After downloading all this data, the build process begins; this can be the most time-consuming step. If you have multiple processing cores, you can run this process with multiple threads.

Kraken2 comes with several databases, such as the SILVA database for 16S rRNA gene analyses. Check the [kraken2 manual](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown) for detailed information on how to download custom things..

```{bash}
#create a kraken2 database 
kraken2-build --standard --threads 24 --db $DBNAME
```


#### Classification

```{bash}
kraken2 --db $DBNAME seqs.fa --output output.out --report output.report
```

### References