---
code-block-bg: true
code-block-border-left: "#31BAE9"
execute:
  eval: false
engine: knitr
bibliography: references.bib
---

## DAS Tool

### Introduction

DAS Tool is an automated method that integrates the results of a flexible number of binning algorithms to calculate an optimized, non-redundant set of bins from a single assembly [@Sieber2018].


### Installation

Installed on Crunchomics: Yes, the following versions of DAS Tool are installed as part of the bioinformatics share:

-   DAS Tool v1.1.7

If you have access to Crunchomics and have not yet access to the bioinformatics you can send an email with your Uva netID to [Nina Dombrowski](n.dombrowski@uva.nl). Afterwards, you can add the bioinformatics share as follows (if you have already done this in the past, you don't need to run this command):

```{bash}
conda config --add envs_dirs /zfs/omics/projects/bioinformatics/software/miniconda3/envs/
```

If you want to install it yourself, you can run:

```{bash}
mamba create -n das_tool_1.1.7 -c bioconda das_tool
```

### Usage

Input file format:

-   Bins \[--bins, -i\]: Tab separated files of contig-IDs and bin-IDs. Contigs to bin file example:

```         
Contig_1    bin.01
Contig_8    bin.01
Contig_42   bin.02
Contig_49   bin.03
```

-   Contigs \[--contigs, -c\]: Assembled contigs in fasta format:

```         
>Contig_1
ATCATCGTCCGCATCGACGAATTCGGCGAACGAGTACCCCTGACCATCTCCGATTA...
>Contig_2
GATCGTCACGCAGGCTATCGGAGCCTCGACCCGCAAGCTCTGCGCCTTGGAGCAGG...
```

-   Proteins (optional) \[--proteins\]: Predicted proteins in prodigal fasta format. Header contains contig-ID and gene number:

```         
>Contig_1_1
MPRKNKKLPRHLLVIRTSAMGDVAMLPHALRALKEAYPEVKVTVATKSLFHPFFEG...
>Contig_1_2
MANKIPRVPVREQDPKVRATNFEEVCYGYNVEEATLEASRCLNCKNPRCVAACPVN...
```

Not all binning tools provide results in a tab separated file of contig-IDs and bin-IDs. A helper script can be used to convert a set of bins in fasta format to tabular contigs2bin file, which can be used as input for DAS Tool: `src/Fasta_to_Contigs2Bin.sh -h`.

```{bash}
src/Fasta_to_Contigs2Bin.sh -i binner/output_folder_with_fasta_files -e fasta > binner.contigs2bin.tsv
```

Example for running the consolidation step:

```{bash}
DAS_Tool  -i sample_data/sample.human.gut_concoct_contigs2bin.tsv,\
	sample_data/sample.human.gut_maxbin2_contigs2bin.tsv,\
	sample_data/sample.human.gut_metabat_contigs2bin.tsv,\
	sample_data/sample.human.gut_tetraESOM_contigs2bin.tsv \
	-l concoct,maxbin,metabat,tetraESOM \
	-c sample_data/sample.human.gut_contigs.fa \
	-o sample_output/DASToolRun1 \
	--write_bins
```

After running this, you fill find all relevant information in the `quality_report.tsv` file in the output folder.

Options:

```
DAS_Tool [options] -i <contig2bin> -c <contigs_fasta> -o <outputbasename>

Options:
   -i --bins=<contig2bin>                   Comma separated list of tab separated contigs to bin tables.
   -c --contigs=<contigs>                   Contigs in fasta format.
   -o --outputbasename=<outputbasename>     Basename of output files.
   -l --labels=<labels>                     Comma separated list of binning prediction names.
   --search_engine=<search_engine>          Engine used for single copy gene identification (diamond/blastp/usearch) [default: diamond].
   -p --proteins=<proteins>                 Predicted proteins (optional) in prodigal fasta format (>contigID_geneNo).
                                            Gene prediction step will be skipped.
   --write_bin_evals                        Write evaluation of input bin sets.
   --write_bins                             Export bins as fasta files.
   --write_unbinned                         Write unbinned contigs.
   -t --threads=<threads>                   Number of threads to use [default: 1].
   --score_threshold=<score_threshold>      Score threshold until selection algorithm will keep selecting bins (0..1) [default: 0.5].
   --duplicate_penalty=<duplicate_penalty>  Penalty for duplicate single copy genes per bin (weight b).
                                            Only change if you know what you are doing (0..3) [default: 0.6].
   --megabin_penalty=<megabin_penalty>      Penalty for megabins (weight c). Only change if you know what you are doing (0..3) [default: 0.5].
   --dbDirectory=<dbDirectory>              Directory of single copy gene database [default: db].
   --resume                                 Use existing predicted single copy gene files from a previous run.
   --debug                                  Write debug information to log file.
   -v --version                             Print version number and exit.
   -h --help                                Show this.
```