---
code-block-bg: true
code-block-border-left: "#31BAE9"
execute:
  eval: false
engine: knitr
bibliography: references.bib
---

<div style="text-align: justify">

## MultiQC

### Introduction

MultiQC is a reporting tool that parses results and statistics from bioinformatics tool outputs, such as log files and console outputs [@Ewels2016]. It helps to summarise experiments containing multiple samples and multiple analysis steps. It’s designed to be placed at the end of pipelines or to be run manually when you’ve finished running your tools. For more information, visit the [official website](https://multiqc.info/docs/).

### Installation

Installed on crunchomics: Yes,

-   MultiQC v1.14.6 is installed as part of the bioinformatics share. If you have access to crunchomics and have not yet access to the bioinformatics you can send an email with your Uva netID to [Nina Dombrowski](n.dombrowski@uva.nl).
-   Afterwards, you can add the bioinformatics share as follows (if you have already done this in the past, you don't need to run this command):

```{bash}
conda config --add envs_dirs /zfs/omics/projects/bioinformatics/software/miniconda3/envs/
```

If you want to install it yourself, you can run:

```{bash}
mamba create --name multiqc_1.22.1 -c bioconda multiqc
```

### Usage

There isn’t much to running MultiQC really - just point it at the directory that contains your files and it will search recursively for anything it recognises. It, for example, can run on reports from FastQC, TrimGalore, Cutadapt, STAR and featureCounts.

```{bash}
conda activate multiqc_1.22.1
multiqc fastqc_folder
```

Once MultiQC has finished, you should have a HTML report file called `multiqc_report.html` that you can open in any browser. 

You can also convert some of the intermediate files into data frames in R for reports. If you are interested in that, have a look at [TidyMultiqc](https://cran.r-project.org/web/packages/TidyMultiqc/index.html)
